blog_index:
    path:     /
    defaults: { _controller: BlogBundle:Post:index }

blog_home:
    path:     /blog
    defaults: { _controller: BlogBundle:Post:index }

blog_create:
    path:     /blog/create
    defaults: { _controller: BlogBundle:Post:create }

blog_show:
    path:     /blog/{postId}
    defaults: { _controller: BlogBundle:Post:show }
